### ISSUE TITLE
PushServer Build Error

### ISSUE THREAD

**Issue by roman921111** [lucaconte/BeatTheMaddler#5]
I have tried to install PushServer, but unfortunately it fails.
though I see some jar files in /target directory.

`$ git clone https://github.com/WhisperSystems/PushServer.git`
`$ cd PushServer`
`$ mvn clean install`

Here is installation log:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.whispersystems.pushserver.controllers.PushControllerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.047 sec
Running org.whispersystems.pushserver.controllers.FeedbackControllerTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.419 sec

Results :

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.2:jar (default-jar) @ Push-Server ---
[INFO] Building jar: /usr/local/src/PushServer/target/Push-Server-0.12.0.jar
[INFO]
[INFO] --- capsule-maven-plugin:0.10.0:build (default) @ Push-Server ---
Jul 26, 2016 9:44:41 AM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: capsule.CapsuleMojo
com.google.inject.ProvisionException: Guice provision errors:

1) No implementation for org.eclipse.aether.RepositorySystem was bound.
  while locating capsule.CapsuleMojo
1 error
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:999)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.jav:1025)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeerredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProvideInternalFactory.java:84)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.proision(InternalFactoryToInitializableAdapter.java:52)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInernalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.rovision(ProvisionListenerStackCallback.java:100)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvison(PlexusLifecycleManager.java:138)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.rovision(ProvisionListenerStackCallback.java:108)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(rovisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProvierInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.getInternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:90)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.jva:1036)
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:986)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntr.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexuBean.java:49)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContaner.java:253)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContaner.java:245)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfigredMojo(DefaultMavenPluginManager.java:455)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaulBuildPluginManager.java:92)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecuto.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecuto.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecuto.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProjct(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProjct(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecyceStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpljava:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccesorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laucher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jaa:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Luncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java356)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.476s
[INFO] Finished at: Tue Jul 26 09:44:41 UTC 2016
[INFO] Final Memory: 24M/59M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.chrischristo:capsule-maven-plugin:0.1.0:build (default) on project Push-Server: Execution default of goal com.githubchrischristo:capsule-maven-plugin:0.10.0:build failed: Unable to load the mojo build' (or one of its required components) from the plugin 'com.github.chrischrsto:capsule-maven-plugin:0.10.0': com.google.inject.ProvisionException: Guice povision errors:
[ERROR]
[ERROR] 1) No implementation for org.eclipse.aether.RepositorySystem was bound.
[ERROR] while locating capsule.CapsuleMojo
[ERROR] at ClassRealm[plugin>com.github.chrischristo:capsule-maven-plugin:0.10., parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.nject.name.Named(value=com.github.chrischristo:capsule-maven-plugin:0.10.0:buil)
[ERROR]
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: com.github.chrischristo:capsule-maven-plugin:0.10.0:build
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swich.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please red the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainrException
```

**Comment by roman921111** [comment]
ahh its successful now. the problem is maven version.

**Comment by ZennouRachid** [comment]
I have the same probleme, Please How did you fix it?

**Comment by lucaconte** [comment]
As @roman921111 said it's a Maven version problem: use a more recente version of maven  
https://lmgtfy.com/?q=No%20implementation%20for%20org.eclipse.aether.RepositorySystem%20was%20bound
